build: release workflow check if version already published to npm [nobuild]

diff --git a/.github/workflows/release.node.yml b/.github/workflows/release.node.yml
--- a/.github/workflows/release.node.yml
+++ b/.github/workflows/release.node.yml
@@ -23,7 +23,8 @@ jobs:
     name: Build package and publish to npm
     runs-on: ubuntu-latest
     outputs:
-      version: ${{ steps.variables.outputs.version }}
+      version: ${{ steps.build.outputs.version }}
+      exists: ${{ steps.build.outputs.exists }}
     steps:
       - uses: actions/checkout@v3
 
@@ -32,14 +33,20 @@ jobs:
         with:
           node-version: '18.x'
 
-      - name: Install dependencies and set APP_VERSION output variable
+      - id: build
+        name: Install dependencies, build and set APP_VERSION output variable
         run: |
           yarn run bootstrap
+          yarn run build
           APP_VERSION=$(node --eval="process.stdout.write(require('./packages/contensis-cli/package.json').version)")
+          VERSION_EXISTS=$(npm view contensis-cli@$APP_VERSION version || false)
+          [ -z "$VERSION_EXISTS" ] && echo "v$APP_VERSION is not found in npm.js" || echo "v$APP_VERSION already published in npm.js"
+          [ "$APP_VERSION" == "$VERSION_EXISTS" ] && npm view contensis-cli@$APP_VERSION
           echo "version=$APP_VERSION" >> $GITHUB_OUTPUT
+          echo "exists=$VERSION_EXISTS" >> $GITHUB_OUTPUT
 
-      - name: Publish release package "${{ steps.variables.outputs.version }}" with tag "${{ inputs.tag }}"
-        if: inputs.tag != 'prerelease'
+      - name: Publish release package "${{ steps.build.outputs.version }}" with tag "${{ inputs.tag }}"
+        if: steps.build.outputs.exists != steps.build.outputs.version
         run: |
           cd packages/contensis-cli
           npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
